### ISSUE TITLE
Plan to release training codes?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [WarranWeng/ET-Net#1]
Any plan to release training codes?

**Comment by Adeelyousaf** [comment]
Any plan for releasing training code?

**Comment by WarranWeng** [comment]
Sorry for not releasing training code due to future plan of our project.

**Comment by ChidanandKumarKS** [comment]
Please keep your codes yourself. We are not interested Great

**Comment by Adeelyousaf** [comment]
> Sorry for not releasing training code due to future plan of our project.

Understanable. Thankyou for your response.
